In [1]:
import numpy as np

a = np.array((10,20,30,40))
print(a)

b = np.arange(1,11)
print(b)

c = np.linspace(0,1,5)
print(c)

[10 20 30 40]
[ 1  2  3  4  5  6  7  8  9 10]
[0.   0.25 0.5  0.75 1.  ]


In [4]:
A = np.array(([1,2],
             [3,4]))
B = np.array(([5,6],
             [7,8]))
print(A+B)
print(A-B)
print(A*B)
print(A%B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[1 2]
 [3 4]]


In [5]:
#Statistics
marks = np.array((70,60,80,90,88))
print(np.mean((marks)))
print(np.max((marks)))
print(np.min((marks)))
print(np.std((marks)))

77.6
90
60
11.271202242884296


In [27]:
#task
#Get weather report of a specific region
#Find the hottest and coldest days
#Find average temperature
#find dates having >35 degree celcius

import csv

filename = "export.csv"

with open(filename, "r") as file:
  reader = csv.DictReader(file)

  highest_temp = float("-inf")
  lowest_temp = float("inf")

  for row in reader:
    temperature = float(row["temp"])

    if temperature > highest_temp:
      highest_temp = temperature
    elif temperature < lowest_temp:
      lowest_temp = temperature

print("hottest day:",highest_temp)
print("lowest day:",lowest_temp)




hottest day: 30.0
lowest day: 23.0
